// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Note: dotenv/config import removed for production compatibility
// Railway and other platforms provide environment variables directly
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
